### ISSUE TITLE
get_list_config is defined twice in virtualmin-mailmain-lib.cgi

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-mailman#1]
Looks like the second one is cleaner, and newer, and I think that's the one that would be actually used (I think Perl gives you the second when you redefine it, except for callers before the second definition, but I'm not confident of that). So, it's probably right to kill the first definition, but I'd rather you make that call.

**Comment by jcameron** [comment]
Oh god that's horrible .. I have no idea how I implemented this function twice, with only partially overlapping functionality! I've checked in a fix.
